# Build and Publish Pipeline
# Triggers when a github release is published - this is "detected" by a tag starting with 'v' being pushed on main branch, part of the github release process

trigger:
  branches:
    exclude:
    - '*'  # Don't trigger on any branch commits
  tags:
    include:
    - v*  # Only trigger on version tags

pr: none

variables:
  solution: 'src/NSwag.Examples.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  packageOutputPath: '.nupkgs'  # should match PackageOutputPath in src/Directory.Build.props

stages:
- stage: Build
  displayName: 'Build and Test'
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'windows-latest'
    steps:
    - template: templates/build-steps.yml
      parameters:
        solution: '$(solution)'
        buildPlatform: '$(buildPlatform)'
        buildConfiguration: '$(buildConfiguration)'
        packageOutputPath: '$(packageOutputPath)'

    - publish: '$(Build.SourcesDirectory)/$(packageOutputPath)'
      artifact: packages
      displayName: 'Publish NuGet packages as artifact'

- stage: Publish
  displayName: 'Publish to NuGet'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: PublishJob
    displayName: 'Publish NuGet packages'
    pool:
      vmImage: 'windows-latest'
    environment: 'nuget-production'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: packages
            displayName: 'Download NuGet packages'

          - task: NuGetCommand@2
            displayName: 'NuGet push'
            inputs:
              command: push
              packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg'
              nuGetFeedType: external
              publishFeedCredentials: TBA_Doncaster Nuget
