# CI Build Pipeline
# Runs on every commit to main to verify build and tests pass

trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'src/NSwag.Examples.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- template: templates/build-steps.yml
  parameters:
    solution: '$(solution)'
    buildPlatform: '$(buildPlatform)'
    buildConfiguration: '$(buildConfiguration)'
